# debug:disable_logs = false

monitor=,preferred,auto,1
source = ~/.config/hypr/monitors.conf

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/mediakeys.conf
source = ~/.config/hypr/startup.conf
# source = ~/.config/hypr/satrtup.local.conf
source = ~/.config/hypr/windowrules.conf
$mainMod = SUPER
source = ~/.config/hypr/binds.conf

# Some default env vars.
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# yay gnome-themes-extra
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

$cur_th = Bibata-Modern-Classic
$cur_size = 38
env = HYPRCURSOR_THEME,$cur_th
env = HYPRCURSOR_SIZE,$cur_size

env = XCURSOR_THEME,$cur_th
env = XCURSOR_SIZE,$cur_size
exec-once = echo "Xcursor.theme:$cur_th" | xrdb -merge
cursor {
    hide_on_key_press = true
    no_warps = true
}

general {
    gaps_in = 1
    gaps_out = 0
    border_size = 0
    col.active_border = 0x000000
    col.inactive_border = 0x000000
    layout = scrolling
}

scrolling {
    fullscreen_on_one_column = true
    direction = right
    column_width = 1.0
    follow_min_visible = 0.9
}

master {
    new_status = master
    orientation = left
    mfact = 0.5
}

decoration {
    rounding = 3
    blur {
        enabled = false
    }
}

animations {
    enabled = true

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

misc {
    disable_splash_rendering = true
    disable_hyprland_logo = true
}

input {
    kb_layout = us,ru
    kb_options = caps:none
    follow_mouse = 1
    sensitivity = -0.6
    touchpad {
        natural_scroll = true
    }
    numlock_by_default = false
}
bind = SUPER, Space, exec, hyprctl switchxkblayout all next && pkill -RTMIN+10 waybar
exec-once = hyprctl keyword input:numlock_by_default false

gesture = 3, horizontal, workspace

device {
    name = gaomon-gaomon-tablet-1
    region_position = 0 0
    region_size = 2048 1152
}

xwayland {
    force_zero_scaling = true
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# clipboard
bind = $mainMod, V, exec, cliphist list \
   | wofi --dmenu --pre-display-cmd "echo '%s' | cut -f 2" \
   | cliphist decode | wl-copy --trim-newline \
   && hyprctl dispatch sendshortcut "CTRL SHIFT,V,"
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# local changes / device specific configs
source = ~/.config/hypr/local.conf
