# default apps for workspaces
exec-once = ~/.config/hyprland_scripts/setup_screen_share.sh
exec-once = hyprpaper
# exec-once = hypridle &
$run_zellij = hyprctl switchxkblayout all 0; kitty -e zellij a main
exec-once=[workspace special:magic silent] $run_zellij
bind = SUPER SHIFT, Q, exec, $run_zellij
# keyring
# exec-once=[workspace special:magic silent] seahorse
exec-once = systemctl --user start hyprpolkitagent

exec-once = waybar &
bind = SUPER SHIFT, B, exec, killall -SIGUSR1 waybar
bind = SUPER CTRL, B, exec, pkill waybar && waybar

exec-once = dropbox &

exec-once = [workspace 1 silent] zen-browser https://www.youtube.com/feed/subscriptions
# always put cursor on primary monitor
exec-once = sleep 5 && hyprctl dispatch workspace 1

exec-once=[workspace 2 silent] vesktop --enable-features=UseOzonePlatform --ozone-platform=x11
# code:58 is "M"
bind = Control_L, code:58, sendshortcut, Control_L&Shift_L, M, class:vesktop
windowrule {
    name = vesktop
    match:class = vesktop
    float = true
    size = (monitor_w*0.8) (monitor_h*0.8)
    move = (monitor_w*0.2) (monitor_h*0.1)
    workspace = 2
}

exec-once = [workspace 2] Telegram
windowrule {
    name = telegram
    match:class = org.telegram.desktop
    float = true
    size = (monitor_w*0.7) (monitor_h*0.9)
    move = 0 (monitor_h*0.05)
    workspace = 2
}

exec-once=[workspace 2 silent] spotify-launcher
windowrule {
    name = spotify
    match:class = spotify
    float = true
    size = (monitor_w*0.8) (monitor_h*0.8)
    move = (monitor_w*0.1) (monitor_h*0.2)
    workspace = 2
}

exec-once=[workspace 3 silent] obsidian
windowrule {
    name = obsidian
    match:class = (?i)obsidian
    float = true
    size = (monitor_w*0.8) (monitor_h*0.8)
    workspace = 3
}

exec-once=[workspace 4 silent] hiddify
exec-once=[workspace 4 silent] ~/.local/bin/TgWsProxy_linux_amd64
