windowrule = float on, match:class (xdg-desktop-portal-gtk)

windowrule = float on, match:class (org.gnome.Nautilus)
windowrule = size 1100 750, match:class (org.gnome.Nautilus)
windowrule = float on, match:initial_title (Save File)
windowrule = size 1100 750, match:title (Save File)
windowrule = float on, match:class org.gnome.NautilusPreviewer

windowrule = immediate on, match:title Overwatch
windowrule = fullscreen_state 2 2, match:title Overwatch
windowrule = fullscreen_state 2 2, match:title Hearthstone
windowrule = fullscreen_state 2 2, match:title "Path of Exile 2"

windowrule {
    name = Picture-in-Picture
    match:title = Picture-in-Picture
    float = true
    size = (monitor_w*0.4) (monitor_h*0.4)
    move = (monitor_w*0.6-1) (monitor_h*0.6-1)
    pin = true
}

windowrule = no_blur on, match:class zen
windowrule = rounding 0, match:class zen

windowrule = float on, match:class mpv
windowrule = center on, match:class mpv
windowrule = size (monitor_w*0.45) (monitor_h*0.45), match:class mpv

windowrule = float on, match:class org.gnome.Calendar
windowrule = size (monitor_w*0.5) (monitor_h*0.85), match:class org.gnome.Calendar
windowrule = animation slide, match:class org.gnome.Calendar

# only works w/ ge-proton
windowrule = tile on, match:title Battle.net
windowrule = float on, match:class steam
windowrule = tile on, match:title Steam
windowrule = float on, match:class Rustdesk

windowrule = float on, match:class timeshift-gtk
windowrule = center on, match:class timeshift-gtk

windowrule = float on, match:class kitty-fzf-picker
windowrule = size (monitor_w*0.5) (monitor_h*0.5), match:class kitty-fzf-picker
