windowrule = float on, match:class (xdg-desktop-portal-gtk)

windowrule = float on, match:class (org.gnome.Nautilus)
windowrule = size 1100 750, match:class (org.gnome.Nautilus)
windowrule = float on, match:initial_title (Save File)
windowrule = size 1100 750, match:title (Save File)
windowrule = float on, match:class org.gnome.NautilusPreviewer

windowrule = fullscreen_state 2 2, match:title Overwatch.*
windowrule = fullscreen_state 2 2, match:title Hearthstone
windowrule = fullscreen_state 2 2, match:title "Path of Exile 2"

windowrule {
    name = Picture-in-Picture
    match:title = Picture-in-Picture
    float = true
    size = (monitor_w*0.4) (monitor_h*0.4)
    move = (monitor_w*0.6-1) (monitor_h*0.6-1)
    pin = true
}

windowrule {
    name = zen
    match:class = zen
    rounding = 0
    no_blur = true
    border_size = 0
}

windowrule = float on, match:class mpv
windowrule = center on, match:class mpv
windowrule = size (monitor_w*0.45) (monitor_h*0.45), match:class mpv

windowrule {
    name = gnome-calendar
    match:class = org.gnome.Calendar
    float = true
    # TODO: window_w wont calculate correctly
    move = (monitor_w*0.31) (monitor_h*0.05)
    animation = slide
}

# only works w/ ge-proton
windowrule {
  name = battlenet
  match:title = Battle.net.*
  tile = true
  fullscreen_state = 1 2
  workspace = 4
}
windowrule = float on, match:class steam
windowrule = tile on, match:title Steam
windowrule = float on, match:class Rustdesk

windowrule = float on, match:class timeshift-gtk
windowrule = center on, match:class timeshift-gtk

windowrule {
    name = kitty-fzf-picker
    match:class = kitty-fzf-picker
    float = true
    size = (monitor_w*0.5) (monitor_h*0.5)
}

windowrule {
    name = kitty-pulsemixer
    match:class = kitty-pulsemixer
    float = true
    size = (monitor_w*0.5) (monitor_h*0.5)
    move = (monitor_w*0.5) (monitor_h*0.05)
    animation = slide
}

windowrule {
    name = kitty-btop
    match:class = kitty-btop
    float = true
    size = (monitor_w*0.7) (monitor_h*0.7)
    move = (monitor_w*0.3) (monitor_h*0.05)
    animation = slide
}
